FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["robot", "--pythonpath", ".", "--variablefile", "config/env_openshift.py", "--outputdir", "results", "./suites/"]