pipeline {
    agent any

    environment {
        DOCKER_USER   = 'pvmrmoorthy' // Your Docker Hub username
        OPENSHIFT_URL = 'https://api.rm3.7wse.p1.openshiftapps.com:6443' // Your Sandbox API URL
    }

    stages {
        stage('Checkout Source Code') {
            steps {
                git branch: 'master', url: 'https://github.com/crazydude552/robot-enterprise-framework.git'
            }
        }

        stage('Build & Push Docker Images') {
    steps {
        dir('RobotFramework_Tutorial/robot-enterprise-framework') {
            withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DH_USER', passwordVariable: 'DH_PASS')]) {
                sh '''
                    echo "$DH_PASS" | docker login -u "$DH_USER" --password-stdin

                    # Force clean build without using cached layers
                    docker build --no-cache -t pvmrmoorthy/fastapi-app:latest .
                    docker push pvmrmoorthy/fastapi-app:latest

                    docker build --no-cache -f Dockerfile.rf -t pvmrmoorthy/rf-runner:latest .
                    docker push pvmrmoorthy/rf-runner:latest
                '''
            }
        }
    }
}

        stage('Deploy FastAPI to OpenShift') {
    steps {
        withCredentials([string(credentialsId: 'openshift-token', variable: 'OS_TOKEN')]) {
            sh '''
                oc login --token=${OS_TOKEN} --server=https://api.rm3.7wse.p1.openshiftapps.com:6443
                oc project pvmrmoorthy-dev

                oc create deployment fastapi-app --image=pvmrmoorthy/fastapi-app:latest --dry-run=client -o yaml | oc apply -f -
                oc expose deployment/fastapi-app --port=8000 --dry-run=client -o yaml | oc apply -f -
                oc create route edge fastapi-app --service=fastapi-app --dry-run=client -o yaml | oc apply -f -

                # Force OpenShift to deploy the newly pushed container image
                oc rollout restart deployment/fastapi-app
                oc rollout status deployment/fastapi-app --timeout=120s
            '''
        }
    }
}

        stage('Execute Robot Framework Tests') {
            steps {
                withCredentials([string(credentialsId: 'openshift-token', variable: 'OS_TOKEN')]) {
                    // Run Robot Framework Test Job
                    sh 'oc delete job rf-test-job --ignore-not-found=true'
                    sh 'oc create job rf-test-job --image=${DOCKER_USER}/rf-runner:latest'

                    // Stream live logs
                    sh 'oc wait --for=condition=complete job/rf-test-job --timeout=120s'
                    sh 'oc logs job/rf-test-job'
                }
            }
        }
    }
}